// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer or VsctGenerator
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BreakpointAssistant
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBreakpointAssistantPackageString = "22b2b6ca-7aa6-433d-b541-c079257991be";
        public const string guidBreakpointAssistantPackageCmdSetString = "A8B9C7D6-E5F4-3A2B-1C0D-9E8F7A6B5C4D";

        public static Guid guidBreakpointAssistantPackage = new Guid(guidBreakpointAssistantPackageString);
        public static Guid guidBreakpointAssistantPackageCmdSet = new Guid(guidBreakpointAssistantPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BreakpointAssistantMenuGroup = 0x1020;
        public const int BreakpointAssistantSubMenu = 0x1100;
        public const int BreakpointAssistantSubMenuGroup = 0x1150;
        public const int ListFunctionLineNumbersCommandId = 0x0100;
    }
}
